version: '3'
services:
  chat_io_node:
    image: node:11
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/www/kite/storage/framework/sessions:/sessions
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start 
    environment:
      - PORT=68605
    tty: true
    ports:
      - 68605:68605
    links:
      - mongo

  chat_io_mongo:
    image: mongo
    volumes:
      - ./db:/data/db