version: '3'
services:
  chat_io_node:
    container_name: chat_io_node
    image: node:11
    restart: always
    volumes:
      - ./:/app
      - ../kiteprop/storage/framework/sessions:/sessions
      - /etc/letsencrypt/live/kiteprop.com-0001/cert.pem:/certs/cert.pem
      - /etc/letsencrypt/live/kiteprop.com-0001/privkey.pem:/certs/priv.key

    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start 
    environment:
      - PORT=443
      - MONGO_HOST=chat_io_mongo
    tty: true
    ports:
      - 6860:443

  chat_io_mongo:
    container_name: chat_io_mongo
    image: mongo
    volumes:
      - ./db:/data/db