version: '3'
services:
  chat_io_node:
    container_name: chat_io_node
    image: node:11
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/www/kite/storage/framework/sessions:/sessions
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start 
    environment:
      - PORT=6860
    tty: true
    ports:
      - 6860:6860
    links:
      - chat_io_mongo

  chat_io_mongo:
    container_name: chat_io_mongo
    image: mongo
    volumes:
      - ./db:/data/db